## NOTE:  Do not edit this file.
## Autogenerated by ProjNav (creatfdo.tcl) on Mon Jan 26 12:17:18 Московское время (зима) 2009
##
vlib work

vcom -93 "../../../lib/vicg/vicg_common_pkg.vhd"

vcom -93 "../../prom_phypin_pkg.vhd"
vcom -93 "../../prog_flash.vhd"

vlog +incdir+../testbanch/include "../testbanch/x28fxxxp30.v"

vcom -93 "../testbanch/prog_flash_tb.vhd"

vsim -t 1ps   -lib work prog_flash_tb
#vsim +notimingchecks -L unisims_ver -t 1ps   -lib work prog_flash_tb
do prog_flash_wave.do
view wave
view structure
view signals
run 1000ns

