## NOTE:  Do not edit this file.
## Autogenerated by ProjNav (creatfdo.tcl) on Mon Jan 26 12:17:18 Московское время (зима) 2009
##

vcom "../../../../lib/vicg/vicg_common_pkg.vhd"
vcom "../../core_gen/sim_fifo_v00.vhd"

vcom "../../core_gen/vcoldemosaic_bram.vhd"
#vcom "../../vcoldemosaic_main_rev2xx.vhd"
vcom "../../vcoldemosaic_main_rev3xx.vhd"

vcom "../testbanch/vcoldemosaic_main_tb.vhd"
