## NOTE:  Do not edit this file.
## Autogenerated by ProjNav (creatfdo.tcl) on Mon Jan 26 12:17:18 Московское время (зима) 2009
##
vlib work


vcom -93 "../../../lib/vicg/vicg_common_pkg.vhd"
vcom -93 "../testbanch/prj_cfg_sim.vhd"

#vcom "../../../../../../ml505/ise/src/core_gen/host_vbuf.vhd"
#vcom "../../../../../../ust/ise/src/core_gen/host_vbuf.vhd"
#vcom "../../../../../../dini_k7/ise/src/core_gen/host_vbuf.vhd"
#vcom -93 "../testbanch/host_vbuf.vhd"
#vcom -93 "../testbanch/host_ethg_txfifo.vhd"
#vcom -93 "../testbanch/host_ethg_rxfifo.vhd"
vcom -93 "../../../../../../dini_k7/ise/src/core_gen/host_ethg_txfifo.vhd"
vcom -93 "../../../../../../dini_k7/ise/src/core_gen/host_ethg_rxfifo.vhd"
#vcom -93 "../../../../../../htg_v6/ise/src/core_gen/ethg_vctrl_rxfifo.vhd"

#vcom "../../../../../../dini_k7/ise/src/eth/eth_phypin_pkg.vhd"
vcom -93 "../../src/eth_phypin_pkg.vhd"
vcom -93 "../../src/eth_pkg.vhd"
vcom -93 "../../src/eth_mac_tx_128b.vhd"
vcom -93 "../../src/eth_mac_rx_128b.vhd"
#vcom -93 "../../src/eth_mac_tx.vhd"
#vcom -93 "../../src/eth_mac_rx.vhd"

vcom -93 "../testbanch/eth_mac_tb.vhd"


vsim -t 1ps   -lib work eth_mac_tb
do eth_mac_tb_wave.do
view wave
view structure
view signals
run 1000ns

