## NOTE:  Do not edit this file.
## Autogenerated by ProjNav (creatfdo.tcl) on Mon Jan 26 12:17:18 Московское время (зима) 2009
##

vcom -93 "../../../lib/vicg/vicg_common_pkg.vhd"

vcom -93 "../../src/eth_phypin_pkg.vhd"
vcom -93 "../../src/eth_pkg.vhd"
vcom -93 "../../src/eth_mdio.vhd"

vcom -93 "../testbanch/eth_mdio_tb.vhd"


##vcom -93 "../../../../hw/lib/vicg/vicg_common_pkg.vhd"
##
##
##vcom -93 "../../../prj_def.vhd"
##vcom -93 "../../core_gen/emac_core/example_design/client/address_swap_module_8.vhd"
##vcom -93 "../../core_gen/emac_core/example_design/client/fifo/tx_client_fifo_8.vhd"
##vcom -93 "../../core_gen/emac_core/example_design/client/fifo/rx_client_fifo_8.vhd"
##vcom -93 "../../core_gen/emac_core/example_design/client/fifo/eth_fifo_8.vhd"
##vcom -93 "../testbanch/example_design/physical/gtp_dual_1000X.vhd"
##vcom -93 "../testbanch/example_design/physical/rocketio_wrapper_gtp.vhd"
##vcom -93 "../testbanch/example_design/physical/rocketio_wrapper_gtp_tile.vhd"
##vcom -93 "../testbanch/example_design/emac_core.vhd"
##vcom -93 "../testbanch/example_design/emac_core_block.vhd"
##vcom -93 "../testbanch/example_design/emac_core_locallink.vhd"
##vcom -93 "../../src/emac_core_main.vhd"
##vcom -93 "../../src/eth_pkg.vhd"
##vcom -93 "../../src/eth_rx_pkt_filter.vhd"
##vcom -93 "../../src/eth_tx_rev1xx.vhd"
##vcom -93 "../../src/eth_rx_rev1xx.vhd"
##vcom -93 "../../src/eth_main.vhd"
##vcom -93 "../../dsn_eth_pkg.vhd"
##vcom -93 "../../dsn_eth.vhd"
##
##
##vcom -93 "../testbanch/dsn_eth_tb.vhd"


