## NOTE:  Do not edit this file.
## Autogenerated by ProjNav (creatfdo.tcl) on Mon Jan 26 12:17:18 Московское время (зима) 2009
##
vcom "../../../../../lib_vicg/vicg_common_pkg.vhd"

vcom "../../lib/GenXlib_utils.vhd"
vcom "../../lib/color_space_pkg.vhd"
vcom "../../lib/GenXlib_arch.vhd"
vcom "../../lib/Xil_RGB2YCrCb.vhd"
vcom "../../lib/Xil_YCrCb2RGB.vhd"

vcom "../../core_gen/vcg_rgb2ycrcb.vhd"
vcom "../../core_gen/vcg_ycrcb2rgb.vhd"
vcom "../../vrgb2yuv_main.vhd"
vcom "../../vyuv2rgb_main.vhd"

vcom "../Testbanch/vrgb2yuv_main_tb.vhd"
