## NOTE:  Do not edit this file.
## Autogenerated by ProjNav (creatfdo.tcl) on Mon Jan 26 12:17:18 Московское время (зима) 2009
##

vcom "../../../../lib/vicg/vicg_common_pkg.vhd"
vcom "../../../../lib/vicg/test_im_pkg.vhd"

vcom "../../core_gen/vsobel_fifo.vhd"
vcom "../../core_gen/vsobel_bram.vhd"
vcom "../../core_gen/vsobel_sub.vhd"
vcom "../../vsobel_main.vhd"

vcom "../testbanch/vsobel_main_tb.vhd"
