## NOTE:  Do not edit this file.
## Autogenerated by ProjNav (creatfdo.tcl) on Mon Jan 26 12:17:18 Московское время (зима) 2009
##
vlib work

vcom -93 "../../../lib/vicg/vicg_common_pkg.vhd"

vcom -93 "../testbanch/prj_cfg_sim.vhd"
vcom -93 "../../src/eth_phypin_pkg.vhd"
vcom -93 "../../src/eth_pkg.vhd"
vcom -93 "../../src/eth_mdio.vhd"

vcom -93 "../testbanch/eth_mdio_tb.vhd"

vsim -t 1ps   -lib work eth_mdio_tb
do eth_mdio_wave.do
view wave
view structure
view signals
run 1000ns

