## NOTE:  Do not edit this file.
## Autogenerated by ProjNav (creatfdo.tcl) on Mon Jan 26 12:17:18 Московское время (зима) 2009
##

vcom -93 "../../../lib/vicg/vicg_common_pkg.vhd"

vcom -93 "../../../uart/src/bbfifo_16x8.vhd"
vcom -93 "../../../uart/src/kcuart_rx.vhd"
vcom -93 "../../../uart/src/kcuart_tx.vhd"
vcom -93 "../../../uart/src/uart_rx.vhd"
vcom -93 "../../../uart/src/uart_tx.vhd"
vcom -93 "../../../uart/uart_main_rev01.vhd"

vcom -93 "../../../cfgdev_ctrl/cfgdev_pkg.vhd"
vcom -93 "../../core_gen/*.vhd"
vcom -93 "../../cfgdev_ftdi.vhd"
vcom -93 "../../cfgdev_uart.vhd"

vcom -93 "../testbanch/cfgdev_ftdi_tb.vhd"
