#!/bin/bash

rm ./*.o
rm ./udp-broadcast-client

gcc -c -D_GNU_SOURCE -Wall -Wreturn-type -g udp-broadcast-client.c
gcc -c -D_GNU_SOURCE -Wall -Wreturn-type -g mkaddr.c
gcc -g udp-broadcast-client.o mkaddr.o -o udp-broadcast-client

printf 'compilation is complete!!!\n'