## NOTE:  Do not edit this file.
## Autogenerated by ProjNav (creatfdo.tcl) on Mon Jan 26 12:17:18 Московское время (зима) 2009
##
vcom "../testbanch/prj_cfg.vhd"
vcom "../testbanch/mem_glob_pkg.vhd"
vcom "../../../lib/hw/lib/vicg/vicg_common_pkg.vhd"
vcom "../../../prj_def.vhd"

#vcom "../../../lib/hw/xapp/xapp930/GenXlib_utils.vhd"
#vcom "../../../lib/hw/xapp/xapp930/color_space_pkg.vhd"
#vcom "../../../lib/hw/xapp/xapp930/GenXlib_arch.vhd"
#vcom "../../../lib/hw/xapp/xapp930/Xil_RGB2YCrCb.vhd"
##vcom "../../../lib/hw/xapp/xapp931/Xil_YCrCb2RGB.vhd"

vcom "../../../lib/hw/mem/alphadata/mem_wr_pkg.vhd"
vcom "../../../lib/hw/mem/alphadata/mem_wr.vhd"

vcom "../../../lib/hw/video/color_demosaic/core_gen/*.vhd"
#vcom "../../../lib/hw/video/color_demosaic/vcoldemosaic_main_rev2xx.vhd"
vcom "../../../lib/hw/video/color_demosaic/vcoldemosaic_main_rev3xx.vhd"

vcom "../../../lib/hw/video/pcolor/core_gen/*.vhd"
vcom "../../../lib/hw/video/pcolor/*.vhd"

vcom "../../../lib/hw/video/gamma/core_gen/*.vhd"
vcom "../../../lib/hw/video/gamma/*.vhd"

vcom "../../../lib/hw/video/scaler/core_gen/*.vhd"
#vcom "../../../lib/hw/video/scaler/vscaler_main_rev2xx.vhd"
vcom "../../../lib/hw/video/scaler/vscaler_main_rev3xx.vhd"

vcom "../../../lib/hw/video/sobel/core_gen/*.vhd"
#vcom "../../../lib/hw/video/sobel/vsobel_main_rev2xx.vhd"
vcom "../../../lib/hw/video/sobel/vsobel_main_rev3xx.vhd"

vcom "../../../mirror/core_gen/*.vhd"
vcom "../../../mirror/*.vhd"

#vcom "../../../color_conv/vrgb2yuv_main_rev0xx.vhd"

vcom "../../dsn_video_ctrl_pkg.vhd"
vcom "../../video_writer_test.vhd"
vcom "../../video_reader.vhd"
#vcom "../testbanch/vbuf_rotate.vhd"
vcom "../testbanch/vctrl_main_tb.vhd"
