## NOTE:  Do not edit this file.
## Autogenerated by ProjNav (creatfdo.tcl) on Mon Jan 26 12:17:18 Московское время (зима) 2009
##
vcom "../../../../hw/lib/vicg/vicg_common_pkg.vhd"
vcom "../../../prj_def.vhd"
vcom "../../../../../ml505/ise/ml505_prj_cfg.vhd"
#vcom "../../../../../alpha5T1/ise/ml505_prj_cfg.vhd"

vcom "../../../../hw/xapp/xapp930/GenXlib_utils.vhd"
vcom "../../../../hw/xapp/xapp930/color_space_pkg.vhd"
vcom "../../../../hw/xapp/xapp930/GenXlib_arch.vhd"
vcom "../../../../hw/xapp/xapp930/Xil_RGB2YCrCb.vhd"
#vcom "../../../../hw/xapp/xapp931/Xil_YCrCb2RGB.vhd"

vcom "../../../../hw/lib/alphadata/admxrc/vhdl/common/memif/memif_pkg.vhd"
vcom "../../../../hw/lib/alphadata/admxrc/vhdl/common/memif/memif_int_pkg.vhd"
vcom "../../../../hw/mem/alphadata/memory_ctrl_pkg.vhd"
vcom "../../../../hw/mem/alphadata/memory_ctrl_ch_wr.vhd"

vcom "../../../../hw/video/color_demosaic/core_gen/*.vhd"
#vcom "../../../../hw/video/color_demosaic/vcoldemosaic_main_rev2xx.vhd"
vcom "../../../../hw/video/color_demosaic/vcoldemosaic_main_rev3xx.vhd"

vcom "../../../../hw/video/pcolor/core_gen/*.vhd"
vcom "../../../../hw/video/pcolor/*.vhd"

vcom "../../../../hw/video/gamma/core_gen/*.vhd"
vcom "../../../../hw/video/gamma/*.vhd"

vcom "../../../../hw/video/scaler/core_gen/*.vhd"
#vcom "../../../../hw/video/scaler/vscaler_main_rev2xx.vhd"
vcom "../../../../hw/video/scaler/vscaler_main_rev3xx.vhd"

vcom "../../../../hw/video/sobel/core_gen/*.vhd"
#vcom "../../../../hw/video/sobel/vsobel_main_rev2xx.vhd"
vcom "../../../../hw/video/sobel/vsobel_main_rev3xx.vhd"

vcom "../../../mirror/core_gen/*.vhd"
vcom "../../../mirror/*.vhd"

vcom "../../../color_conv/vrgb2yuv_main.vhd"

vcom "../../dsn_video_ctrl_pkg.vhd"
vcom "../../video_reader.vhd"
vcom "../testbanch/vctrl_main_tb.vhd"
