## NOTE:  Do not edit this file.
## Autogenerated by ProjNav (creatfdo.tcl) on Mon Jan 26 12:17:18 Московское время (зима) 2009
##
vlib work

vcom "../testbanch/prj_cfg.vhd"
vcom "../testbanch/mem_glob_pkg.vhd"
vcom "../../../lib/hw/lib/vicg/vicg_common_pkg.vhd"
vcom "../../../prj_def.vhd"

vcom "../../../lib/hw/mem/alphadata/mem_wr_pkg.vhd"
vcom "../../../lib/hw/mem/alphadata/mem_wr.vhd"

vcom "../../../../ml505/ise/src/core_gen/host_vbuf.vhd"

vcom "../../dsn_video_ctrl_pkg.vhd"
vcom "../../video_writer_test.vhd"
vcom "../testbanch/vwriter_tb.vhd"

vsim -t 1ps   -lib work vwriter_tb
#do vctrl_main_tb_wave.do
view wave
view structure
view signals
run 1000ns

