## NOTE:  Do not edit this file.
## Autogenerated by ProjNav (creatfdo.tcl) on Mon Jan 26 12:17:18 Московское время (зима) 2009
##
vlib work

vcom "../../lib/vicg_common_pkg.vhd"
vcom "../../../../../prj_def.vhd"
vcom "../../vtester_v01.vhd"
vcom "../../core_gen/vtester_fifo.vhd"
vcom "../Testbanch/vtester_v01_tb.vhd"
vsim -t 1ps   -lib work vtester_v01_tb
do vtester_v01_wave.do
view wave
view structure
view signals
run 1000ns

