## NOTE:  Do not edit this file.
## Autogenerated by ProjNav (creatfdo.tcl) on Mon Jan 26 12:17:18 Московское время (зима) 2009
##

vcom -93 "../../../lib/vicg_common_pkg.vhd"

vcom -93 "../../../xapp/xapp691/src/vhdl/fifo_utils.vhd"
vcom -93 "../../../xapp/xapp691/src/vhdl/BRAM/BRAM_S8_S72.vhd"
vcom -93 "../../../xapp/xapp691/src/vhdl/BRAM/BRAM_S72_S72.vhd"
vcom -93 "../../../xapp/xapp691/src/vhdl/BRAM/BRAM_S36_S72.vhd"
vcom -93 "../../../xapp/xapp691/src/vhdl/BRAM/BRAM_S18_S72.vhd"
vcom -93 "../../../xapp/xapp691/src/vhdl/DRAM/RAM_64nX1.vhd"
vcom -93 "../../../xapp/xapp691/src/vhdl/DRAM/DRAM_fifo_pkg.vhd"
vcom -93 "../../../xapp/xapp691/src/vhdl/BRAM/BRAM_S8_S144.vhd"
vcom -93 "../../../xapp/xapp691/src/vhdl/BRAM/BRAM_S72_S144.vhd"
vcom -93 "../../../xapp/xapp691/src/vhdl/BRAM/BRAM_S36_S144.vhd"
vcom -93 "../../../xapp/xapp691/src/vhdl/BRAM/BRAM_S16_S144.vhd"
vcom -93 "../../../xapp/xapp691/src/vhdl/BRAM/BRAM_S144_S144.vhd"
vcom -93 "../../../xapp/xapp691/src/vhdl/BRAM/BRAM_fifo_pkg.vhd"
vcom -93 "../../../xapp/xapp691/src/vhdl/DRAM/DRAM_macro.vhd"
vcom -93 "../../../xapp/xapp691/src/vhdl/BRAM/BRAM_macro.vhd"
vcom -93 "../../../xapp/xapp691/src/vhdl/DRAM/DRAM_fifo.vhd"
vcom -93 "../../../xapp/xapp691/src/vhdl/BRAM/BRAM_fifo.vhd"
vcom -93 "../../../xapp/xapp691/src/vhdl/ll_fifo_pkg.vhd"
vcom -93 "../../../xapp/xapp691/src/vhdl/ll_fifo_DRAM.vhd"
vcom -93 "../../../xapp/xapp691/src/vhdl/ll_fifo_BRAM.vhd"
vcom -93 "../../../xapp/xapp691/src/vhdl/ll_fifo.vhd"
vcom -93 "../../core_gen/sata_rxfifo.vhd"
vcom -93 "../../core_gen/sata_txfifo.vhd"
vcom -93 "../../core_gen/sata_cmdfifo.vhd"

vcom -93 "../../src/sata_pkg.vhd"
vcom -93 "../../src/sata_sim_lite_pkg.vhd"
vcom -93 "../../src/sata_unit_pkg.vhd"

vcom -93 "../../src/sata_dcm.vhd"
vcom -93 "../../src/sata_rocketio.vhd"

vcom -93 "../../src/sata_scrambler.vhd"
vcom -93 "../../src/sata_crc.vhd"

vcom -93 "../../src/sata_spd_ctrl.vhd"

vcom -93 "../../src/sata_player_oob.vhd"
vcom -93 "../../src/sata_player_rx.vhd"
vcom -93 "../../src/sata_player_tx.vhd"
vcom -93 "../../src/sata_player.vhd"
vcom -93 "../../src/sata_llayer.vhd"
vcom -93 "../../src/sata_tlayer.vhd"
vcom -93 "../../src/sata_alayer.vhd"

vcom -93 "../../src/sata_host.vhd"

vcom -93 "../../src/sata_connector.vhd"
vcom -93 "../../src/sata_raid_dmux.vhd"
vcom -93 "../../src/sata_raid_ctrl.vhd"
vcom -93 "../../src/sata_raid.vhd"

vcom -93 "../../src/dsn_raid_main.vhd"

vcom -93 "../testbanch/sata_sim_pkg.vhd"
vcom -93 "../testbanch/sata_bufdata.vhd"
vcom -93 "../testbanch/sata_dev_model.vhd"
vcom -93 "../testbanch/sata_player_tb.vhd"
vcom -93 "../testbanch/sata_host_tb.vhd"
vcom -93 "../testbanch/dsn_raid_main_tb.vhd"