#ChipScope Core Inserter Project File Version 3.0
#Tue Oct 02 15:25:00 GST 2012
Project.device.designInputFile=D\:\\Work\\Linkos\\veresk_m\\ml505\\ise\\prj\\ethphy_test_main_cs.ngc
Project.device.designOutputFile=D\:\\Work\\Linkos\\veresk_m\\ml505\\ise\\prj\\ethphy_test_main_cs.ngc
Project.device.deviceFamily=14
Project.device.enableRPMs=true
Project.device.outputDirectory=D\:\\Work\\Linkos\\veresk_m\\ml505\\ise\\prj\\_ngo
Project.device.useSRL16=true
Project.filter.dimension=19
Project.filter<0>=
Project.filter<10>=m_eth/gen_use_on.m_main/m_phy/m_if/m_emac_ll/rx_g*
Project.filter<11>=m_eth/gen_use_on.m_main/m_phy/m_if/m_emac_ll/rx_b*
Project.filter<12>=m_eth/gen_use_on.m_main/m_phy/m_if/m_emac_ll/tx_d*
Project.filter<13>=m_eth/gen_use_on.m_main/m_phy/m_if/emac_ll/tx_d*
Project.filter<14>=m_eth/gen_use_on.m_main/m_phy/m_if/*
Project.filter<15>=m_eth/gen_use_on.m_main/m_phy/m_if/emac_ll/tx_vd
Project.filter<16>=m_eth/gen_use_on.m_main/m_phy/m_if/emac_ll/tx_v*
Project.filter<17>=m_eth/gen_use_on.m_main/m_phy/m_if/emac_ll/tx_a*
Project.filter<18>=m_eth/gen_use_on.m_main/m_phy/m_if/emac_ll/rx_d*
Project.filter<1>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/m_mdio/i_m*
Project.filter<2>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/m_mdio/sr_rx*
Project.filter<3>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/m_mdio/sr_tx*
Project.filter<4>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/m_mdio/i_tx*
Project.filter<5>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/m_mdio/**
Project.filter<6>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/i_e*
Project.filter<7>=m_eth/gen_use_on.m_main/m_phy/m_if/m_emac_ll/tx_a*
Project.filter<8>=m_eth/gen_use_on.m_main/m_phy/m_if/m_emac_ll/rx_d*
Project.filter<9>=m_eth/gen_use_on.m_main/m_phy/m_if/m_emac_ll/rx_v*
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=i_ethphy_out_clk
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_tx/i_ll_data<0>
Project.unit<0>.dataChannel<100>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/i_mdio_start
Project.unit<0>.dataChannel<101>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/i_phy_err
Project.unit<0>.dataChannel<102>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/i_phy_link
Project.unit<0>.dataChannel<103>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/i_phy_cfg_done
Project.unit<0>.dataChannel<104>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/m_mdio/i_txd_en
Project.unit<0>.dataChannel<105>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/m_mdio/i_mdc
Project.unit<0>.dataChannel<106>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/m_mdio/sr_txd<0>
Project.unit<0>.dataChannel<107>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/m_mdio/sr_txd<1>
Project.unit<0>.dataChannel<108>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/m_mdio/sr_txd<2>
Project.unit<0>.dataChannel<109>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/m_mdio/sr_txd<3>
Project.unit<0>.dataChannel<10>=m_eth/gen_use_on.m_main/m_phy/m_if/m_emac_ll/rx_bad_frame_0_r
Project.unit<0>.dataChannel<110>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/m_mdio/sr_txd<4>
Project.unit<0>.dataChannel<111>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/m_mdio/sr_txd<5>
Project.unit<0>.dataChannel<112>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/m_mdio/sr_txd<6>
Project.unit<0>.dataChannel<113>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/m_mdio/sr_txd<7>
Project.unit<0>.dataChannel<114>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/m_mdio/sr_txd<8>
Project.unit<0>.dataChannel<115>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/m_mdio/sr_txd<9>
Project.unit<0>.dataChannel<116>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/m_mdio/sr_txd<10>
Project.unit<0>.dataChannel<117>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/m_mdio/sr_txd<11>
Project.unit<0>.dataChannel<118>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/m_mdio/sr_txd<12>
Project.unit<0>.dataChannel<119>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/m_mdio/sr_txd<13>
Project.unit<0>.dataChannel<11>=m_eth/gen_use_on.m_main/m_phy/m_if/m_emac_ll/rx_data_0_r<0>
Project.unit<0>.dataChannel<120>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/m_mdio/sr_txd<14>
Project.unit<0>.dataChannel<121>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/m_mdio/sr_txd<15>
Project.unit<0>.dataChannel<122>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/m_mdio/sr_rxd<0>
Project.unit<0>.dataChannel<123>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/m_mdio/sr_rxd<1>
Project.unit<0>.dataChannel<124>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/m_mdio/sr_rxd<2>
Project.unit<0>.dataChannel<125>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/m_mdio/sr_rxd<3>
Project.unit<0>.dataChannel<126>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/m_mdio/sr_rxd<4>
Project.unit<0>.dataChannel<127>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/m_mdio/sr_rxd<5>
Project.unit<0>.dataChannel<128>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/m_mdio/sr_rxd<6>
Project.unit<0>.dataChannel<129>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/m_mdio/sr_rxd<7>
Project.unit<0>.dataChannel<12>=m_eth/gen_use_on.m_main/m_phy/m_if/m_emac_ll/rx_data_0_r<1>
Project.unit<0>.dataChannel<130>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/m_mdio/sr_rxd<8>
Project.unit<0>.dataChannel<131>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/m_mdio/sr_rxd<9>
Project.unit<0>.dataChannel<132>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/m_mdio/sr_rxd<10>
Project.unit<0>.dataChannel<133>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/m_mdio/sr_rxd<11>
Project.unit<0>.dataChannel<134>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/m_mdio/sr_rxd<12>
Project.unit<0>.dataChannel<135>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/m_mdio/sr_rxd<13>
Project.unit<0>.dataChannel<136>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/m_mdio/sr_rxd<14>
Project.unit<0>.dataChannel<137>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/m_mdio/sr_rxd<15>
Project.unit<0>.dataChannel<13>=m_eth/gen_use_on.m_main/m_phy/m_if/m_emac_ll/rx_data_0_r<2>
Project.unit<0>.dataChannel<14>=m_eth/gen_use_on.m_main/m_phy/m_if/m_emac_ll/rx_data_0_r<3>
Project.unit<0>.dataChannel<15>=m_eth/gen_use_on.m_main/m_phy/m_if/m_emac_ll/rx_data_0_r<4>
Project.unit<0>.dataChannel<16>=m_eth/gen_use_on.m_main/m_phy/m_if/m_emac_ll/rx_data_0_r<5>
Project.unit<0>.dataChannel<17>=m_eth/gen_use_on.m_main/m_phy/m_if/m_emac_ll/rx_data_0_r<6>
Project.unit<0>.dataChannel<18>=m_eth/gen_use_on.m_main/m_phy/m_if/m_emac_ll/rx_data_0_r<7>
Project.unit<0>.dataChannel<19>=m_eth/gen_use_on.m_main/m_phy/m_if/m_emac_ll/rx_data_valid_0_i
Project.unit<0>.dataChannel<1>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_tx/i_ll_data<1>
Project.unit<0>.dataChannel<20>=m_eth/gen_use_on.m_main/m_phy/m_if/m_emac_ll/rx_good_frame_0_r
Project.unit<0>.dataChannel<21>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_tx/tst_fms_cs_dly<0>
Project.unit<0>.dataChannel<22>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_tx/tst_fms_cs_dly<1>
Project.unit<0>.dataChannel<23>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_tx/tst_fms_cs_dly<2>
Project.unit<0>.dataChannel<24>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_rx/tst_fms_cs_dly<0>
Project.unit<0>.dataChannel<25>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_rx/tst_fms_cs_dly<1>
Project.unit<0>.dataChannel<26>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_rx/tst_fms_cs_dly<2>
Project.unit<0>.dataChannel<27>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_rx/tst_rxll_eof_n
Project.unit<0>.dataChannel<28>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_rx/tst_rxll_sof_n
Project.unit<0>.dataChannel<29>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_rx/tst_rxll_src_rdy_n
Project.unit<0>.dataChannel<2>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_tx/i_ll_data<2>
Project.unit<0>.dataChannel<30>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_rx/i_ll_dst_rdy_n
Project.unit<0>.dataChannel<31>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_rx/i_dcnt<0>
Project.unit<0>.dataChannel<32>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_rx/i_dcnt<1>
Project.unit<0>.dataChannel<33>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_rx/i_dcnt<2>
Project.unit<0>.dataChannel<34>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_rx/i_dcnt<3>
Project.unit<0>.dataChannel<35>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_rx/i_dcnt<4>
Project.unit<0>.dataChannel<36>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_rx/i_dcnt<5>
Project.unit<0>.dataChannel<37>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_rx/i_dcnt<6>
Project.unit<0>.dataChannel<38>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_rx/i_dcnt<7>
Project.unit<0>.dataChannel<39>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_rx/i_dcnt<8>
Project.unit<0>.dataChannel<3>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_tx/i_ll_data<3>
Project.unit<0>.dataChannel<40>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_rx/i_dcnt<9>
Project.unit<0>.dataChannel<41>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_rx/i_dcnt<10>
Project.unit<0>.dataChannel<42>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_rx/i_dcnt<11>
Project.unit<0>.dataChannel<43>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_rx/i_dcnt<12>
Project.unit<0>.dataChannel<44>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_rx/i_dcnt<13>
Project.unit<0>.dataChannel<45>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_rx/i_dcnt<14>
Project.unit<0>.dataChannel<46>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_rx/i_dcnt<15>
Project.unit<0>.dataChannel<47>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/i_phy_rst
Project.unit<0>.dataChannel<48>=m_eth_txbuf rd_en
Project.unit<0>.dataChannel<49>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_rx/i_rx_mac.lentype_0
Project.unit<0>.dataChannel<4>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_tx/i_ll_data<4>
Project.unit<0>.dataChannel<50>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_rx/i_rx_mac.lentype_1
Project.unit<0>.dataChannel<51>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_rx/i_rx_mac.lentype_2
Project.unit<0>.dataChannel<52>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_rx/i_rx_mac.lentype_3
Project.unit<0>.dataChannel<53>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_rx/i_rx_mac.lentype_4
Project.unit<0>.dataChannel<54>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_rx/i_rx_mac.lentype_5
Project.unit<0>.dataChannel<55>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_rx/i_rx_mac.lentype_6
Project.unit<0>.dataChannel<56>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_rx/i_rx_mac.lentype_7
Project.unit<0>.dataChannel<57>=m_eth/h_reg_ethcfg.mac.src_1_0
Project.unit<0>.dataChannel<58>=m_eth/h_reg_ethcfg.mac.src_1_1
Project.unit<0>.dataChannel<59>=m_eth/h_reg_ethcfg.mac.src_1_2
Project.unit<0>.dataChannel<5>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_tx/i_ll_data<5>
Project.unit<0>.dataChannel<60>=m_eth/h_reg_ethcfg.mac.src_1_3
Project.unit<0>.dataChannel<61>=m_eth/h_reg_ethcfg.mac.src_1_4
Project.unit<0>.dataChannel<62>=m_eth/h_reg_ethcfg.mac.src_1_5
Project.unit<0>.dataChannel<63>=m_eth/h_reg_ethcfg.mac.src_1_6
Project.unit<0>.dataChannel<64>=m_eth/h_reg_ethcfg.mac.src_1_7
Project.unit<0>.dataChannel<65>=i_eth_cfg_done
Project.unit<0>.dataChannel<66>=m_eth_txbuf wr_en
Project.unit<0>.dataChannel<67>=m_eth_txbuf din<0>
Project.unit<0>.dataChannel<68>=m_eth_txbuf din<1>
Project.unit<0>.dataChannel<69>=m_eth_txbuf din<2>
Project.unit<0>.dataChannel<6>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_tx/i_ll_data<6>
Project.unit<0>.dataChannel<70>=m_eth_txbuf din<3>
Project.unit<0>.dataChannel<71>=m_eth_txbuf din<4>
Project.unit<0>.dataChannel<72>=m_eth_txbuf din<5>
Project.unit<0>.dataChannel<73>=m_eth_txbuf din<6>
Project.unit<0>.dataChannel<74>=m_eth_txbuf din<7>
Project.unit<0>.dataChannel<75>=m_eth_txbuf din<8>
Project.unit<0>.dataChannel<76>=m_eth_txbuf din<9>
Project.unit<0>.dataChannel<77>=m_eth_txbuf din<10>
Project.unit<0>.dataChannel<78>=m_eth_txbuf din<11>
Project.unit<0>.dataChannel<79>=m_eth_txbuf din<12>
Project.unit<0>.dataChannel<7>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_tx/i_ll_data<7>
Project.unit<0>.dataChannel<80>=m_eth_txbuf din<13>
Project.unit<0>.dataChannel<81>=m_eth_txbuf din<14>
Project.unit<0>.dataChannel<82>=m_eth_txbuf din<15>
Project.unit<0>.dataChannel<83>=m_eth_txbuf din<16>
Project.unit<0>.dataChannel<84>=m_eth_txbuf din<17>
Project.unit<0>.dataChannel<85>=m_eth_txbuf din<18>
Project.unit<0>.dataChannel<86>=m_eth_txbuf din<19>
Project.unit<0>.dataChannel<87>=m_eth_txbuf din<20>
Project.unit<0>.dataChannel<88>=m_eth_txbuf din<21>
Project.unit<0>.dataChannel<89>=m_eth_txbuf din<22>
Project.unit<0>.dataChannel<8>=m_eth/gen_use_on.m_main/m_app/gen_ch[0].m_mac_tx/i_ll_src_rdy_n
Project.unit<0>.dataChannel<90>=m_eth_txbuf din<23>
Project.unit<0>.dataChannel<91>=m_eth_txbuf din<24>
Project.unit<0>.dataChannel<92>=m_eth_txbuf din<25>
Project.unit<0>.dataChannel<93>=m_eth_txbuf din<26>
Project.unit<0>.dataChannel<94>=m_eth_txbuf din<27>
Project.unit<0>.dataChannel<95>=m_eth_txbuf din<28>
Project.unit<0>.dataChannel<96>=m_eth_txbuf din<29>
Project.unit<0>.dataChannel<97>=m_eth_txbuf din<30>
Project.unit<0>.dataChannel<98>=m_eth_txbuf din<31>
Project.unit<0>.dataChannel<99>=i_eth_cfg_wr
Project.unit<0>.dataChannel<9>=m_eth/gen_use_on.m_main/m_phy/m_if/m_emac_ll/tx_ack_0_i
Project.unit<0>.dataDepth=8192
Project.unit<0>.dataEqualsTrigger=false
Project.unit<0>.dataPortWidth=138
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=m_eth/gen_use_on.m_main/m_phy/m_if/m_emac_ll/tx_data_valid_0_i
Project.unit<0>.triggerChannel<0><1>=m_eth/gen_use_on.m_main/m_phy/m_if/m_emac_ll/rx_data_valid_0_i
Project.unit<0>.triggerChannel<0><2>=m_eth/gen_use_on.m_main/m_phy/m_if/m_emac_ll/rx_bad_frame_0_r
Project.unit<0>.triggerChannel<0><3>=m_eth/gen_use_on.m_main/m_phy/m_if/m_emac_ll/rx_good_frame_0_r
Project.unit<0>.triggerChannel<0><4>=m_eth/gen_use_on.m_main/m_phy/m_if/m_emac_ll/tx_ack_0_i
Project.unit<0>.triggerChannel<0><5>=m_eth_txbuf wr_en
Project.unit<0>.triggerChannel<0><6>=i_eth_cfg_done
Project.unit<0>.triggerChannel<0><7>=m_eth/gen_use_on.m_main/m_phy/m_if/m_mdio_ctrl/i_mdio_start
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerPortCount=1
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortWidth<0>=8
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
