## NOTE:  Do not edit this file.
## Autogenerated by ProjNav (creatfdo.tcl) on Mon Jan 19 12:34:48 Московское время (зима) 2009
##
vlib work
vcom -93 "../../../lib/vicg/vicg_common_pkg.vhd"

vcom -93 "../../src/sata_crc.vhd"
vcom -93 "../testbanch/sata_crc_tb.vhd"
vsim -t 1ps   -lib work sata_crc_tb
do {sata_crc_tb_wave.do}
view wave
view structure
view signals
run 1200ns
