## NOTE:  Do not edit this file.
## Autogenerated by ProjNav (creatfdo.tcl) on Mon Jan 26 12:17:18 Московское время (зима) 2009
##
vlib work

do updata_dsn_hdd_tb.do

vsim -t 1ps   -lib work hdd_main_tb
do hdd_main3_tb_wave.do
view wave
view structure
view signals
run 1000ns

