######################################################################
#
# File name : eth_core_tb_compile.do
# Created on: Wed Nov 04 11:57:38 +0300 2015
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
file delete -force -- work

vlib work

vlog -64  "../../uart8_rx.v";
vlog -64  "../../uart8_tx.v";

vcom -64 -93 "../testbanch/uartrx_tb.vhd";

vsim -t 1ps  -nocoverage -novopt -lib work uartrx_tb
#vsim -t 1ps -nocoverage -lib work rpnv_dsp_top_tb

do uartrx_tb_wave.do
view wave
view structure
view signals
run 90 us

#quit -force


