## NOTE:  Do not edit this file.
## Autogenerated by ProjNav (creatfdo.tcl) on Mon Jan 26 12:17:18 Московское время (зима) 2009
##

vcom "../../../../../lib_vicg/vicg_common_pkg.vhd"

vcom "../../../Sobel/core_gen/vsobel_fifo.vhd"
vcom "../../../Sobel/core_gen/vsobel_bram.vhd"
vcom "../../../Sobel/core_gen/vsobel_sub.vhd"
vcom "../../../Sobel/vsobel_main.vhd"

vcom "../../../../../prj_def.vhd"
vcom "../../dsn_track_nik_pkg.vhd"
vcom "../../core_gen/trc_nik_mult.vhd"
vcom "../../core_gen/trc_nik_ramang.vhd"
vcom "../../trc_nik_grado.vhd"

vcom "../Testbanch/vsobel_grado_tb.vhd"

