## NOTE:  Do not edit this file.
## Autogenerated by ProjNav (creatfdo.tcl) on Mon Jan 26 12:17:18 Московское время (зима) 2009
##

vcom "../../../../lib/vicg/vicg_common_pkg.vhd"
vcom "../../../../lib/vicg/test_im_pkg.vhd"

vcom "../../core_gen/vscale_fifo.vhd"
vcom "../../core_gen/vscale_bram.vhd"
vcom "../../core_gen/vscale_bram_coef.vhd"
vcom "../../vscaler_main.vhd"

vcom "../testbanch/vscaler_main_tb.vhd"


