## NOTE:  Do not edit this file.
## Autogenerated by ProjNav (creatfdo.tcl) on Mon Jan 26 12:17:18 Московское время (зима) 2009
##
vlib work

vcom "../../lib/vicg_common_pkg.vhd"
vcom "../../vmirx_main.vhd"
vcom "../../core_gen/vmirx_fifo.vhd"
vcom "../../core_gen/vmirx_bram.vhd"
vcom "../Testbanch/vmirx_main_tb.vhd"
vsim -t 1ps   -lib work vmirx_main_tb
do vmirx_main_tb_wave.do
view wave
view structure
view signals
run 1000ns

