onerror {resume}
quietly virtual function -install /brightness_tb/brightness_m -env /brightness_tb { &{/brightness_tb/brightness_m/mr[15], /brightness_tb/brightness_m/mr[14], /brightness_tb/brightness_m/mr[13], /brightness_tb/brightness_m/mr[12], /brightness_tb/brightness_m/mr[11], /brightness_tb/brightness_m/mr[10], /brightness_tb/brightness_m/mr[9], /brightness_tb/brightness_m/mr[8], /brightness_tb/brightness_m/mr[7], /brightness_tb/brightness_m/mr[6] }} mr_i
quietly virtual function -install /brightness_tb/brightness_m -env /brightness_tb { &{/brightness_tb/brightness_m/mr[5], /brightness_tb/brightness_m/mr[4], /brightness_tb/brightness_m/mr[3], /brightness_tb/brightness_m/mr[2], /brightness_tb/brightness_m/mr[1], /brightness_tb/brightness_m/mr[0] }} mr_f
quietly virtual function -install /brightness_tb/brightness_m -env /brightness_tb/brightness_m { &{/brightness_tb/brightness_m/mcoe_x128[15], /brightness_tb/brightness_m/mcoe_x128[14], /brightness_tb/brightness_m/mcoe_x128[13], /brightness_tb/brightness_m/mcoe_x128[12], /brightness_tb/brightness_m/mcoe_x128[11], /brightness_tb/brightness_m/mcoe_x128[10], /brightness_tb/brightness_m/mcoe_x128[9], /brightness_tb/brightness_m/mcoe_x128[8], /brightness_tb/brightness_m/mcoe_x128[7], /brightness_tb/brightness_m/mcoe_x128[6] }} x128_i
quietly virtual function -install /brightness_tb/brightness_m -env /brightness_tb/brightness_m { &{/brightness_tb/brightness_m/mcoe_x128[5], /brightness_tb/brightness_m/mcoe_x128[4], /brightness_tb/brightness_m/mcoe_x128[3], /brightness_tb/brightness_m/mcoe_x128[2], /brightness_tb/brightness_m/mcoe_x128[1], /brightness_tb/brightness_m/mcoe_x128[0] }} x128_f
quietly virtual function -install /brightness_tb/brightness_m -env /brightness_tb { &{/brightness_tb/brightness_m/res_r[13], /brightness_tb/brightness_m/res_r[12], /brightness_tb/brightness_m/res_r[11], /brightness_tb/brightness_m/res_r[10], /brightness_tb/brightness_m/res_r[9], /brightness_tb/brightness_m/res_r[8], /brightness_tb/brightness_m/res_r[7], /brightness_tb/brightness_m/res_r[6] }} res_i
quietly WaveActivateNextPane {} 0
add wave -noupdate /brightness_tb/brightness_m/clk
add wave -noupdate -radix unsigned -childformat {{{/brightness_tb/brightness_m/di[0][8]} -radix hexadecimal} {{/brightness_tb/brightness_m/di[0][7]} -radix hexadecimal} {{/brightness_tb/brightness_m/di[0][6]} -radix hexadecimal} {{/brightness_tb/brightness_m/di[0][5]} -radix hexadecimal} {{/brightness_tb/brightness_m/di[0][4]} -radix hexadecimal} {{/brightness_tb/brightness_m/di[0][3]} -radix hexadecimal} {{/brightness_tb/brightness_m/di[0][2]} -radix hexadecimal} {{/brightness_tb/brightness_m/di[0][1]} -radix hexadecimal} {{/brightness_tb/brightness_m/di[0][0]} -radix hexadecimal}} -subitemconfig {{/brightness_tb/brightness_m/di[0][8]} {-height 15 -radix hexadecimal} {/brightness_tb/brightness_m/di[0][7]} {-height 15 -radix hexadecimal} {/brightness_tb/brightness_m/di[0][6]} {-height 15 -radix hexadecimal} {/brightness_tb/brightness_m/di[0][5]} {-height 15 -radix hexadecimal} {/brightness_tb/brightness_m/di[0][4]} {-height 15 -radix hexadecimal} {/brightness_tb/brightness_m/di[0][3]} {-height 15 -radix hexadecimal} {/brightness_tb/brightness_m/di[0][2]} {-height 15 -radix hexadecimal} {/brightness_tb/brightness_m/di[0][1]} {-height 15 -radix hexadecimal} {/brightness_tb/brightness_m/di[0][0]} {-height 15 -radix hexadecimal}} {/brightness_tb/brightness_m/di[0]}
add wave -noupdate /brightness_tb/brightness_m/contrast
add wave -noupdate -radix hexadecimal -childformat {{{/brightness_tb/brightness_m/mcoe_x128[15]} -radix unsigned} {{/brightness_tb/brightness_m/mcoe_x128[14]} -radix unsigned} {{/brightness_tb/brightness_m/mcoe_x128[13]} -radix unsigned} {{/brightness_tb/brightness_m/mcoe_x128[12]} -radix unsigned} {{/brightness_tb/brightness_m/mcoe_x128[11]} -radix unsigned} {{/brightness_tb/brightness_m/mcoe_x128[10]} -radix unsigned} {{/brightness_tb/brightness_m/mcoe_x128[9]} -radix unsigned} {{/brightness_tb/brightness_m/mcoe_x128[8]} -radix unsigned} {{/brightness_tb/brightness_m/mcoe_x128[7]} -radix unsigned} {{/brightness_tb/brightness_m/mcoe_x128[6]} -radix unsigned} {{/brightness_tb/brightness_m/mcoe_x128[5]} -radix unsigned} {{/brightness_tb/brightness_m/mcoe_x128[4]} -radix unsigned} {{/brightness_tb/brightness_m/mcoe_x128[3]} -radix unsigned} {{/brightness_tb/brightness_m/mcoe_x128[2]} -radix unsigned} {{/brightness_tb/brightness_m/mcoe_x128[1]} -radix unsigned} {{/brightness_tb/brightness_m/mcoe_x128[0]} -radix unsigned}} -subitemconfig {{/brightness_tb/brightness_m/mcoe_x128[15]} {-height 15 -radix unsigned} {/brightness_tb/brightness_m/mcoe_x128[14]} {-height 15 -radix unsigned} {/brightness_tb/brightness_m/mcoe_x128[13]} {-height 15 -radix unsigned} {/brightness_tb/brightness_m/mcoe_x128[12]} {-height 15 -radix unsigned} {/brightness_tb/brightness_m/mcoe_x128[11]} {-height 15 -radix unsigned} {/brightness_tb/brightness_m/mcoe_x128[10]} {-height 15 -radix unsigned} {/brightness_tb/brightness_m/mcoe_x128[9]} {-height 15 -radix unsigned} {/brightness_tb/brightness_m/mcoe_x128[8]} {-height 15 -radix unsigned} {/brightness_tb/brightness_m/mcoe_x128[7]} {-height 15 -radix unsigned} {/brightness_tb/brightness_m/mcoe_x128[6]} {-height 15 -radix unsigned} {/brightness_tb/brightness_m/mcoe_x128[5]} {-height 15 -radix unsigned} {/brightness_tb/brightness_m/mcoe_x128[4]} {-height 15 -radix unsigned} {/brightness_tb/brightness_m/mcoe_x128[3]} {-height 15 -radix unsigned} {/brightness_tb/brightness_m/mcoe_x128[2]} {-height 15 -radix unsigned} {/brightness_tb/brightness_m/mcoe_x128[1]} {-height 15 -radix unsigned} {/brightness_tb/brightness_m/mcoe_x128[0]} {-height 15 -radix unsigned}} /brightness_tb/brightness_m/mcoe_x128
add wave -noupdate /brightness_tb/brightness_m/r_m
add wave -noupdate /brightness_tb/brightness_m/r_m_sum
add wave -noupdate /brightness_tb/brightness_m/r_m_sum_round
add wave -noupdate -radix unsigned -childformat {{{/brightness_tb/brightness_m/do_[0][7]} -radix unsigned} {{/brightness_tb/brightness_m/do_[0][6]} -radix unsigned} {{/brightness_tb/brightness_m/do_[0][5]} -radix unsigned} {{/brightness_tb/brightness_m/do_[0][4]} -radix unsigned} {{/brightness_tb/brightness_m/do_[0][3]} -radix unsigned} {{/brightness_tb/brightness_m/do_[0][2]} -radix unsigned} {{/brightness_tb/brightness_m/do_[0][1]} -radix unsigned} {{/brightness_tb/brightness_m/do_[0][0]} -radix unsigned}} -subitemconfig {{/brightness_tb/brightness_m/do_[0][7]} {-height 15 -radix unsigned} {/brightness_tb/brightness_m/do_[0][6]} {-height 15 -radix unsigned} {/brightness_tb/brightness_m/do_[0][5]} {-height 15 -radix unsigned} {/brightness_tb/brightness_m/do_[0][4]} {-height 15 -radix unsigned} {/brightness_tb/brightness_m/do_[0][3]} {-height 15 -radix unsigned} {/brightness_tb/brightness_m/do_[0][2]} {-height 15 -radix unsigned} {/brightness_tb/brightness_m/do_[0][1]} {-height 15 -radix unsigned} {/brightness_tb/brightness_m/do_[0][0]} {-height 15 -radix unsigned}} {/brightness_tb/brightness_m/do_[0]}
TreeUpdate [SetDefaultTree]
WaveRestoreCursors
quietly wave cursor active 0
configure wave -namecolwidth 245
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {325575 ps}
