onerror {resume}
quietly virtual function -install /brightness_tb/brightness_m -env /brightness_tb/brightness_m { &{/brightness_tb/brightness_m/mcoe_x128[15], /brightness_tb/brightness_m/mcoe_x128[14], /brightness_tb/brightness_m/mcoe_x128[13], /brightness_tb/brightness_m/mcoe_x128[12], /brightness_tb/brightness_m/mcoe_x128[11], /brightness_tb/brightness_m/mcoe_x128[10], /brightness_tb/brightness_m/mcoe_x128[9], /brightness_tb/brightness_m/mcoe_x128[8], /brightness_tb/brightness_m/mcoe_x128[7], /brightness_tb/brightness_m/mcoe_x128[6] }} x128_i
quietly virtual function -install /brightness_tb/brightness_m -env /brightness_tb/brightness_m { &{/brightness_tb/brightness_m/mcoe_x128[5], /brightness_tb/brightness_m/mcoe_x128[4], /brightness_tb/brightness_m/mcoe_x128[3], /brightness_tb/brightness_m/mcoe_x128[2], /brightness_tb/brightness_m/mcoe_x128[1], /brightness_tb/brightness_m/mcoe_x128[0] }} x128_f
quietly virtual function -install /brightness_tb/brightness_m -env /brightness_tb/brightness_m { &{/brightness_tb/brightness_m/r_m[17], /brightness_tb/brightness_m/r_m[16], /brightness_tb/brightness_m/r_m[15], /brightness_tb/brightness_m/r_m[14], /brightness_tb/brightness_m/r_m[13], /brightness_tb/brightness_m/r_m[12], /brightness_tb/brightness_m/r_m[11], /brightness_tb/brightness_m/r_m[10], /brightness_tb/brightness_m/r_m[9], /brightness_tb/brightness_m/r_m[8], /brightness_tb/brightness_m/r_m[7], /brightness_tb/brightness_m/r_m[6] }} r_m_i
quietly virtual function -install /brightness_tb/brightness_m -env /brightness_tb/brightness_m { &{/brightness_tb/brightness_m/g_m[17], /brightness_tb/brightness_m/g_m[16], /brightness_tb/brightness_m/g_m[15], /brightness_tb/brightness_m/g_m[14], /brightness_tb/brightness_m/g_m[13], /brightness_tb/brightness_m/g_m[12], /brightness_tb/brightness_m/g_m[11], /brightness_tb/brightness_m/g_m[10], /brightness_tb/brightness_m/g_m[9], /brightness_tb/brightness_m/g_m[8], /brightness_tb/brightness_m/g_m[7], /brightness_tb/brightness_m/g_m[6] }} g_m_i
quietly virtual function -install /brightness_tb/brightness_m -env /brightness_tb/brightness_m { &{/brightness_tb/brightness_m/b_m[17], /brightness_tb/brightness_m/b_m[16], /brightness_tb/brightness_m/b_m[15], /brightness_tb/brightness_m/b_m[14], /brightness_tb/brightness_m/b_m[13], /brightness_tb/brightness_m/b_m[12], /brightness_tb/brightness_m/b_m[11], /brightness_tb/brightness_m/b_m[10], /brightness_tb/brightness_m/b_m[9], /brightness_tb/brightness_m/b_m[8], /brightness_tb/brightness_m/b_m[7], /brightness_tb/brightness_m/b_m[6] }} b_m_i
quietly virtual function -install /brightness_tb/brightness_m -env /brightness_tb { &{/brightness_tb/brightness_m/r_m_sum[16], /brightness_tb/brightness_m/r_m_sum[15], /brightness_tb/brightness_m/r_m_sum[14], /brightness_tb/brightness_m/r_m_sum[13], /brightness_tb/brightness_m/r_m_sum[12], /brightness_tb/brightness_m/r_m_sum[11], /brightness_tb/brightness_m/r_m_sum[10], /brightness_tb/brightness_m/r_m_sum[9], /brightness_tb/brightness_m/r_m_sum[8], /brightness_tb/brightness_m/r_m_sum[7], /brightness_tb/brightness_m/r_m_sum[6] }} r_m_sum_i
quietly virtual function -install /brightness_tb/brightness_m -env /brightness_tb { &{/brightness_tb/brightness_m/mcoe_x128[17], /brightness_tb/brightness_m/mcoe_x128[16], /brightness_tb/brightness_m/mcoe_x128[15], /brightness_tb/brightness_m/mcoe_x128[14], /brightness_tb/brightness_m/mcoe_x128[13], /brightness_tb/brightness_m/mcoe_x128[12], /brightness_tb/brightness_m/mcoe_x128[11], /brightness_tb/brightness_m/mcoe_x128[10], /brightness_tb/brightness_m/mcoe_x128[9], /brightness_tb/brightness_m/mcoe_x128[8], /brightness_tb/brightness_m/mcoe_x128[7], /brightness_tb/brightness_m/mcoe_x128[6] }} mcoe_x128_i
quietly virtual function -install /brightness_tb/brightness_m -env /brightness_tb { &{/brightness_tb/brightness_m/g_m_sum[16], /brightness_tb/brightness_m/g_m_sum[15], /brightness_tb/brightness_m/g_m_sum[14], /brightness_tb/brightness_m/g_m_sum[13], /brightness_tb/brightness_m/g_m_sum[12], /brightness_tb/brightness_m/g_m_sum[11], /brightness_tb/brightness_m/g_m_sum[10], /brightness_tb/brightness_m/g_m_sum[9], /brightness_tb/brightness_m/g_m_sum[8], /brightness_tb/brightness_m/g_m_sum[7], /brightness_tb/brightness_m/g_m_sum[6] }} g_m_sum_i
quietly virtual function -install /brightness_tb/brightness_m -env /brightness_tb { &{/brightness_tb/brightness_m/b_m_sum[16], /brightness_tb/brightness_m/b_m_sum[15], /brightness_tb/brightness_m/b_m_sum[14], /brightness_tb/brightness_m/b_m_sum[13], /brightness_tb/brightness_m/b_m_sum[12], /brightness_tb/brightness_m/b_m_sum[11], /brightness_tb/brightness_m/b_m_sum[10], /brightness_tb/brightness_m/b_m_sum[9], /brightness_tb/brightness_m/b_m_sum[8], /brightness_tb/brightness_m/b_m_sum[7], /brightness_tb/brightness_m/b_m_sum[6] }} b_m_sum_i
quietly virtual function -install /brightness_tb/brightness_m -env /brightness_tb { &{/brightness_tb/brightness_m/br_sum[15], /brightness_tb/brightness_m/br_sum[14], /brightness_tb/brightness_m/br_sum[13], /brightness_tb/brightness_m/br_sum[12], /brightness_tb/brightness_m/br_sum[11], /brightness_tb/brightness_m/br_sum[10], /brightness_tb/brightness_m/br_sum[9], /brightness_tb/brightness_m/br_sum[8], /brightness_tb/brightness_m/br_sum[7], /brightness_tb/brightness_m/br_sum[6] }} br_sum_i
quietly virtual function -install /brightness_tb/brightness_m -env /brightness_tb { &{/brightness_tb/brightness_m/r_m_sum2[17], /brightness_tb/brightness_m/r_m_sum2[16], /brightness_tb/brightness_m/r_m_sum2[15], /brightness_tb/brightness_m/r_m_sum2[14], /brightness_tb/brightness_m/r_m_sum2[13], /brightness_tb/brightness_m/r_m_sum2[12], /brightness_tb/brightness_m/r_m_sum2[11], /brightness_tb/brightness_m/r_m_sum2[10], /brightness_tb/brightness_m/r_m_sum2[9], /brightness_tb/brightness_m/r_m_sum2[8], /brightness_tb/brightness_m/r_m_sum2[7], /brightness_tb/brightness_m/r_m_sum2[6] }} r_m_sum2_i
quietly virtual function -install /brightness_tb/brightness_m -env /brightness_tb { &{/brightness_tb/brightness_m/g_m_sum2[17], /brightness_tb/brightness_m/g_m_sum2[16], /brightness_tb/brightness_m/g_m_sum2[15], /brightness_tb/brightness_m/g_m_sum2[14], /brightness_tb/brightness_m/g_m_sum2[13], /brightness_tb/brightness_m/g_m_sum2[12], /brightness_tb/brightness_m/g_m_sum2[11], /brightness_tb/brightness_m/g_m_sum2[10], /brightness_tb/brightness_m/g_m_sum2[9], /brightness_tb/brightness_m/g_m_sum2[8], /brightness_tb/brightness_m/g_m_sum2[7], /brightness_tb/brightness_m/g_m_sum2[6] }} g_m_sum2_i
quietly virtual function -install /brightness_tb/brightness_m -env /brightness_tb { &{/brightness_tb/brightness_m/b_m_sum2[17], /brightness_tb/brightness_m/b_m_sum2[16], /brightness_tb/brightness_m/b_m_sum2[15], /brightness_tb/brightness_m/b_m_sum2[14], /brightness_tb/brightness_m/b_m_sum2[13], /brightness_tb/brightness_m/b_m_sum2[12], /brightness_tb/brightness_m/b_m_sum2[11], /brightness_tb/brightness_m/b_m_sum2[10], /brightness_tb/brightness_m/b_m_sum2[9], /brightness_tb/brightness_m/b_m_sum2[8], /brightness_tb/brightness_m/b_m_sum2[7], /brightness_tb/brightness_m/b_m_sum2[6] }} b_m_sum2_i
quietly virtual function -install /brightness_tb/brightness_m -env /brightness_tb { &{/brightness_tb/brightness_m/g_round[18], /brightness_tb/brightness_m/g_round[17], /brightness_tb/brightness_m/g_round[16], /brightness_tb/brightness_m/g_round[15], /brightness_tb/brightness_m/g_round[14], /brightness_tb/brightness_m/g_round[13], /brightness_tb/brightness_m/g_round[12], /brightness_tb/brightness_m/g_round[11], /brightness_tb/brightness_m/g_round[10], /brightness_tb/brightness_m/g_round[9], /brightness_tb/brightness_m/g_round[8], /brightness_tb/brightness_m/g_round[7], /brightness_tb/brightness_m/g_round[6] }} g_round_i
quietly virtual function -install /brightness_tb/brightness_m -env /brightness_tb { &{/brightness_tb/brightness_m/r_round[18], /brightness_tb/brightness_m/r_round[17], /brightness_tb/brightness_m/r_round[16], /brightness_tb/brightness_m/r_round[15], /brightness_tb/brightness_m/r_round[14], /brightness_tb/brightness_m/r_round[13], /brightness_tb/brightness_m/r_round[12], /brightness_tb/brightness_m/r_round[11], /brightness_tb/brightness_m/r_round[10], /brightness_tb/brightness_m/r_round[9], /brightness_tb/brightness_m/r_round[8], /brightness_tb/brightness_m/r_round[7], /brightness_tb/brightness_m/r_round[6] }} r_round_i
quietly virtual function -install /brightness_tb/brightness_m -env /brightness_tb { &{/brightness_tb/brightness_m/b_round[18], /brightness_tb/brightness_m/b_round[17], /brightness_tb/brightness_m/b_round[16], /brightness_tb/brightness_m/b_round[15], /brightness_tb/brightness_m/b_round[14], /brightness_tb/brightness_m/b_round[13], /brightness_tb/brightness_m/b_round[12], /brightness_tb/brightness_m/b_round[11], /brightness_tb/brightness_m/b_round[10], /brightness_tb/brightness_m/b_round[9], /brightness_tb/brightness_m/b_round[8], /brightness_tb/brightness_m/b_round[7], /brightness_tb/brightness_m/b_round[6] }} b_round_i
quietly WaveActivateNextPane {} 0
add wave -noupdate /brightness_tb/brightness_m/clk
add wave -noupdate /brightness_tb/brightness_m/de_i
add wave -noupdate -radix unsigned -childformat {{{/brightness_tb/brightness_m/di[0]} -radix unsigned} {{/brightness_tb/brightness_m/di[1]} -radix unsigned} {{/brightness_tb/brightness_m/di[2]} -radix unsigned}} -expand -subitemconfig {{/brightness_tb/brightness_m/di[0]} {-height 15 -radix unsigned} {/brightness_tb/brightness_m/di[1]} {-height 15 -radix unsigned} {/brightness_tb/brightness_m/di[2]} {-height 15 -radix unsigned}} /brightness_tb/brightness_m/di
add wave -noupdate -radix unsigned /brightness_tb/brightness_m/contrast
add wave -noupdate -radix decimal -childformat {{{/brightness_tb/brightness_m/brightness[7]} -radix decimal} {{/brightness_tb/brightness_m/brightness[6]} -radix decimal} {{/brightness_tb/brightness_m/brightness[5]} -radix decimal} {{/brightness_tb/brightness_m/brightness[4]} -radix decimal} {{/brightness_tb/brightness_m/brightness[3]} -radix decimal} {{/brightness_tb/brightness_m/brightness[2]} -radix decimal} {{/brightness_tb/brightness_m/brightness[1]} -radix decimal} {{/brightness_tb/brightness_m/brightness[0]} -radix decimal}} -subitemconfig {{/brightness_tb/brightness_m/brightness[7]} {-height 15 -radix decimal} {/brightness_tb/brightness_m/brightness[6]} {-height 15 -radix decimal} {/brightness_tb/brightness_m/brightness[5]} {-height 15 -radix decimal} {/brightness_tb/brightness_m/brightness[4]} {-height 15 -radix decimal} {/brightness_tb/brightness_m/brightness[3]} {-height 15 -radix decimal} {/brightness_tb/brightness_m/brightness[2]} {-height 15 -radix decimal} {/brightness_tb/brightness_m/brightness[1]} {-height 15 -radix decimal} {/brightness_tb/brightness_m/brightness[0]} {-height 15 -radix decimal}} /brightness_tb/brightness_m/brightness
add wave -noupdate -divider //stage0
add wave -noupdate -radix unsigned /brightness_tb/brightness_m/mcoe_x128_i
add wave -noupdate -radix unsigned /brightness_tb/brightness_m/br_sum_i
add wave -noupdate -radix unsigned /brightness_tb/brightness_m/r_m_i
add wave -noupdate -radix unsigned /brightness_tb/brightness_m/g_m_i
add wave -noupdate -radix unsigned /brightness_tb/brightness_m/b_m_i
add wave -noupdate -divider //stage1
add wave -noupdate -radix decimal -childformat {{(10) -radix unsigned} {(9) -radix unsigned} {(8) -radix unsigned} {(7) -radix unsigned} {(6) -radix unsigned} {(5) -radix unsigned} {(4) -radix unsigned} {(3) -radix unsigned} {(2) -radix unsigned} {(1) -radix unsigned} {(0) -radix unsigned}} -subitemconfig {{/brightness_tb/brightness_m/r_m_sum[16]} {-radix unsigned} {/brightness_tb/brightness_m/r_m_sum[15]} {-radix unsigned} {/brightness_tb/brightness_m/r_m_sum[14]} {-radix unsigned} {/brightness_tb/brightness_m/r_m_sum[13]} {-radix unsigned} {/brightness_tb/brightness_m/r_m_sum[12]} {-radix unsigned} {/brightness_tb/brightness_m/r_m_sum[11]} {-radix unsigned} {/brightness_tb/brightness_m/r_m_sum[10]} {-radix unsigned} {/brightness_tb/brightness_m/r_m_sum[9]} {-radix unsigned} {/brightness_tb/brightness_m/r_m_sum[8]} {-radix unsigned} {/brightness_tb/brightness_m/r_m_sum[7]} {-radix unsigned} {/brightness_tb/brightness_m/r_m_sum[6]} {-radix unsigned}} /brightness_tb/brightness_m/r_m_sum_i
add wave -noupdate -radix decimal /brightness_tb/brightness_m/g_m_sum_i
add wave -noupdate -radix decimal /brightness_tb/brightness_m/b_m_sum_i
add wave -noupdate -divider //stage2
add wave -noupdate -radix decimal /brightness_tb/brightness_m/r_m_sum2_i
add wave -noupdate -radix decimal /brightness_tb/brightness_m/g_m_sum2_i
add wave -noupdate -radix decimal /brightness_tb/brightness_m/b_m_sum2_i
add wave -noupdate -divider //stage3
add wave -noupdate -radix decimal -childformat {{(12) -radix decimal} {(11) -radix decimal} {(10) -radix decimal} {(9) -radix decimal} {(8) -radix decimal} {(7) -radix decimal} {(6) -radix decimal} {(5) -radix decimal} {(4) -radix decimal} {(3) -radix decimal} {(2) -radix decimal} {(1) -radix decimal} {(0) -radix decimal}} -subitemconfig {{/brightness_tb/brightness_m/r_round[18]} {-radix decimal} {/brightness_tb/brightness_m/r_round[17]} {-radix decimal} {/brightness_tb/brightness_m/r_round[16]} {-radix decimal} {/brightness_tb/brightness_m/r_round[15]} {-radix decimal} {/brightness_tb/brightness_m/r_round[14]} {-radix decimal} {/brightness_tb/brightness_m/r_round[13]} {-radix decimal} {/brightness_tb/brightness_m/r_round[12]} {-radix decimal} {/brightness_tb/brightness_m/r_round[11]} {-radix decimal} {/brightness_tb/brightness_m/r_round[10]} {-radix decimal} {/brightness_tb/brightness_m/r_round[9]} {-radix decimal} {/brightness_tb/brightness_m/r_round[8]} {-radix decimal} {/brightness_tb/brightness_m/r_round[7]} {-radix decimal} {/brightness_tb/brightness_m/r_round[6]} {-radix decimal}} /brightness_tb/brightness_m/r_round_i
add wave -noupdate -radix decimal /brightness_tb/brightness_m/g_round_i
add wave -noupdate -radix decimal -childformat {{(12) -radix decimal} {(11) -radix decimal} {(10) -radix decimal} {(9) -radix decimal} {(8) -radix decimal} {(7) -radix decimal} {(6) -radix decimal} {(5) -radix decimal} {(4) -radix decimal} {(3) -radix decimal} {(2) -radix decimal} {(1) -radix decimal} {(0) -radix decimal}} -subitemconfig {{/brightness_tb/brightness_m/b_round[18]} {-radix decimal} {/brightness_tb/brightness_m/b_round[17]} {-radix decimal} {/brightness_tb/brightness_m/b_round[16]} {-radix decimal} {/brightness_tb/brightness_m/b_round[15]} {-radix decimal} {/brightness_tb/brightness_m/b_round[14]} {-radix decimal} {/brightness_tb/brightness_m/b_round[13]} {-radix decimal} {/brightness_tb/brightness_m/b_round[12]} {-radix decimal} {/brightness_tb/brightness_m/b_round[11]} {-radix decimal} {/brightness_tb/brightness_m/b_round[10]} {-radix decimal} {/brightness_tb/brightness_m/b_round[9]} {-radix decimal} {/brightness_tb/brightness_m/b_round[8]} {-radix decimal} {/brightness_tb/brightness_m/b_round[7]} {-radix decimal} {/brightness_tb/brightness_m/b_round[6]} {-radix decimal}} /brightness_tb/brightness_m/b_round_i
add wave -noupdate -divider //stage4
add wave -noupdate /brightness_tb/brightness_m/clk
add wave -noupdate /brightness_tb/brightness_m/dbg_o
add wave -noupdate /brightness_tb/brightness_m/de_o
add wave -noupdate -radix unsigned -childformat {{{/brightness_tb/brightness_m/do_[0]} -radix unsigned} {{/brightness_tb/brightness_m/do_[1]} -radix unsigned} {{/brightness_tb/brightness_m/do_[2]} -radix unsigned}} -expand -subitemconfig {{/brightness_tb/brightness_m/do_[0]} {-height 15 -radix unsigned} {/brightness_tb/brightness_m/do_[1]} {-height 15 -radix unsigned} {/brightness_tb/brightness_m/do_[2]} {-height 15 -radix unsigned}} /brightness_tb/brightness_m/do_
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
quietly wave cursor active 0
configure wave -namecolwidth 245
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {7837200 ps}
