onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /filter_median_entity_tb/main/clk
add wave -noupdate -radix unsigned -childformat {{{/filter_median_entity_tb/xi[24]} -radix unsigned} {{/filter_median_entity_tb/xi[23]} -radix unsigned} {{/filter_median_entity_tb/xi[22]} -radix unsigned} {{/filter_median_entity_tb/xi[21]} -radix unsigned} {{/filter_median_entity_tb/xi[20]} -radix unsigned} {{/filter_median_entity_tb/xi[19]} -radix unsigned} {{/filter_median_entity_tb/xi[18]} -radix unsigned} {{/filter_median_entity_tb/xi[17]} -radix unsigned} {{/filter_median_entity_tb/xi[16]} -radix unsigned} {{/filter_median_entity_tb/xi[15]} -radix unsigned} {{/filter_median_entity_tb/xi[14]} -radix unsigned} {{/filter_median_entity_tb/xi[13]} -radix unsigned} {{/filter_median_entity_tb/xi[12]} -radix unsigned} {{/filter_median_entity_tb/xi[11]} -radix unsigned} {{/filter_median_entity_tb/xi[10]} -radix unsigned} {{/filter_median_entity_tb/xi[9]} -radix unsigned} {{/filter_median_entity_tb/xi[8]} -radix unsigned} {{/filter_median_entity_tb/xi[7]} -radix unsigned} {{/filter_median_entity_tb/xi[6]} -radix unsigned} {{/filter_median_entity_tb/xi[5]} -radix unsigned} {{/filter_median_entity_tb/xi[4]} -radix unsigned} {{/filter_median_entity_tb/xi[3]} -radix unsigned} {{/filter_median_entity_tb/xi[2]} -radix unsigned} {{/filter_median_entity_tb/xi[1]} -radix unsigned} {{/filter_median_entity_tb/xi[0]} -radix unsigned}} -subitemconfig {{/filter_median_entity_tb/xi[24]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xi[23]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xi[22]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xi[21]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xi[20]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xi[19]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xi[18]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xi[17]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xi[16]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xi[15]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xi[14]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xi[13]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xi[12]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xi[11]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xi[10]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xi[9]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xi[8]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xi[7]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xi[6]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xi[5]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xi[4]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xi[3]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xi[2]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xi[1]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xi[0]} {-height 15 -radix unsigned}} /filter_median_entity_tb/xi
add wave -noupdate -radix unsigned -childformat {{{/filter_median_entity_tb/xo[24]} -radix unsigned} {{/filter_median_entity_tb/xo[23]} -radix unsigned} {{/filter_median_entity_tb/xo[22]} -radix unsigned} {{/filter_median_entity_tb/xo[21]} -radix unsigned} {{/filter_median_entity_tb/xo[20]} -radix unsigned} {{/filter_median_entity_tb/xo[19]} -radix unsigned} {{/filter_median_entity_tb/xo[18]} -radix unsigned} {{/filter_median_entity_tb/xo[17]} -radix unsigned} {{/filter_median_entity_tb/xo[16]} -radix unsigned} {{/filter_median_entity_tb/xo[15]} -radix unsigned} {{/filter_median_entity_tb/xo[14]} -radix unsigned} {{/filter_median_entity_tb/xo[13]} -radix unsigned} {{/filter_median_entity_tb/xo[12]} -radix unsigned} {{/filter_median_entity_tb/xo[11]} -radix unsigned} {{/filter_median_entity_tb/xo[10]} -radix unsigned} {{/filter_median_entity_tb/xo[9]} -radix unsigned} {{/filter_median_entity_tb/xo[8]} -radix unsigned} {{/filter_median_entity_tb/xo[7]} -radix unsigned} {{/filter_median_entity_tb/xo[6]} -radix unsigned} {{/filter_median_entity_tb/xo[5]} -radix unsigned} {{/filter_median_entity_tb/xo[4]} -radix unsigned} {{/filter_median_entity_tb/xo[3]} -radix unsigned} {{/filter_median_entity_tb/xo[2]} -radix unsigned} {{/filter_median_entity_tb/xo[1]} -radix unsigned} {{/filter_median_entity_tb/xo[0]} -radix unsigned}} -expand -subitemconfig {{/filter_median_entity_tb/xo[24]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xo[23]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xo[22]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xo[21]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xo[20]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xo[19]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xo[18]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xo[17]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xo[16]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xo[15]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xo[14]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xo[13]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xo[12]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xo[11]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xo[10]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xo[9]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xo[8]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xo[7]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xo[6]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xo[5]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xo[4]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xo[3]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xo[2]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xo[1]} {-height 15 -radix unsigned} {/filter_median_entity_tb/xo[0]} {-height 15 -radix unsigned}} /filter_median_entity_tb/xo
TreeUpdate [SetDefaultTree]
WaveRestoreCursors
quietly wave cursor active 0
configure wave -namecolwidth 206
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits us
update
WaveRestoreZoom {1417562968 ps} {1434991423 ps}
